class EnvironmentSettings:
    def __init__(self):
        self.workspace_dir = '/content/SDTrack/SDTrack-Event'    # Base directory for saving network checkpoints.
        self.tensorboard_dir = '/content/SDTrack/SDTrack-Event/tensorboard'    # Directory for tensorboard files.
        self.pretrained_networks = '/content/SDTrack/SDTrack-Event/pretrained_models'
        self.lasot_dir = '/data/dataset/lasot'
        self.got10k_dir = '/data/dataset/got10k/train'
        self.got10k_val_dir = '/data/dataset/got10k/val'
        self.lasot_lmdb_dir = '/data/dataset/lasot_lmdb'
        self.got10k_lmdb_dir = '/data/dataset/got10k_lmdb'
        self.trackingnet_dir = '/data/dataset/trackingnet'
        self.trackingnet_lmdb_dir = '/data/dataset/trackingnet_lmdb'
        self.coco_dir = '/data/dataset/coco'
        self.coco_lmdb_dir = '/data/dataset/coco_lmdb'
        self.lvis_dir = ''
        self.sbd_dir = ''
        self.imagenet_dir = '/data/dataset/vid'
        self.imagenet_lmdb_dir = '/data/dataset/vid_lmdb'
        self.imagenetdet_dir = ''
        self.ecssd_dir = ''
        self.hkuis_dir = ''
        self.msra10k_dir = ''
        self.davis_dir = ''
        self.youtubevos_dir = ''
        self.eotb_dir_train = '/data/dataset/FE108/train'
        self.visevent_train = '/data/dataset/VisEvent/train/'
        self.felt_train = '/data/dataset/FELT/train/'
